version:  '3.9'
services:
  app:
    image: victorzero21/untitled
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - my-network-name
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "720M"
networks:
  my-network-name:
    name: springcloud




